### PR TITLE
Fixes to HTTPS support

### PR DESCRIPTION
**Pull request by nre-ableton**
So after https://github.com/emmetog/ansible-jenkins/pull/48 was merged, I noticed a few problems with the role as I was testing it with our infrastructure with the CA signed certificates (I'd previously only used the JKS keystore during testing). As I was fixing this, I also started making a few various cleanups, namely merging the `configure-config.yml` to `configure-jenkins.yml` and improving the README a bit.

Also, this PR adds a molecule test scenario for HTTPS to verify that it works correctly.

ping @emmetog

### CODE REVIEW

**Comment by nre-ableton** [comment]
Travis builds seem to be timing out while installing apt packages. Please let me investigate this a bit before merging.

**Comment by nre-ableton** [comment]
I guess it was just a Travis/apt hiccup, anyways the build is passing now. re-ping @emmetog

**Comment by emmetog** [comment]
Thanks again for the PR @nre-ableton !

**Comment by nre-ableton** [comment]
@emmetog Thank you!

**Pull request merged**
